RobotecAI/ROSCon2023Demo

- .gitmodules
- Project/Assets/Factory/Box2.prefab
- Project/Assets/Factory/EuroPallet.prefab
- Project/Assets/Importer/ur10.prefab
- Project/Levels/otto/otto.prefab
- Project/Levels/sss/sss.prefab
- Project/Prefabs/Cell.prefab
- README.md
- ros2_ws/README.md
- ros2_ws/src/ur_moveit_demo/CMakeLists.txt
- ros2_ws/src/ur_moveit_demo/README.md
- ros2_ws/src/ur_moveit_demo/launch/mtc.launch.py
- ros2_ws/src/ur_moveit_demo/package.xml
- ros2_ws/src/ur_moveit_demo/rviz/view_robot.rviz
- ros2_ws/src/ur_moveit_demo/rviz/view_robot_moveit.rviz
- ros2_ws/src/ur_moveit_demo/src/gripper.cpp
- ros2_ws/src/ur_moveit_demo/src/gripper.h
- ros2_ws/src/ur_moveit_demo/src/mtc.cpp
- ros2_ws/src/ur_moveit_demo/src/taskConstructor.cpp
- ros2_ws/src/ur_moveit_demo/src/taskConstructor.h
- ros2_ws/src/ur_moveit_demo/src/ur_moveit_demo.cpp
- ros2_ws/src/ur_moveit_demo/src/utils.cpp
- ros2_ws/src/ur_moveit_demo/src/utils.h
- ros2_ws/src/ur_moveit_demo/src/vision.cpp
- ros2_ws/src/ur_moveit_demo/src/vision.h
I've combined all of the work done with the Moveit palletization process and refactored it.
This PR is dependent on #26.
> Box palletization using Moveit Task Constructor

- ros2_ws/src/OTTO1500_Description/CMakeLists.txt
- ros2_ws/src/OTTO1500_Description/package.xml
> change otto1500 package name

- Project/Levels/DemoLevel/DemoLevel.prefab
Removed unused levels. Fixed json `op` errors.
> Cleaned levels.

- Project/Prefabs/OTTO600/OTTO600.prefab
- ros2_ws/src/OTTO600_Description/Urdf/OTTO600.urdf.xacro
> Add lidar and lifting module to otto 600

- Project/Prefabs/OTTO600/OTTO600.prefab
- ros2_ws/src/o3de_fleet_nav/params/humble/nav2_multirobot_params.yaml
retargeting https://github.com/RobotecAI/ROSCon2023Demo/pull/89 to main
> Multiple lidars for collision detection

- Project/Gem/Source/Vision/IdealVisionSystem.cpp
I've added namespace from ROS2FrameComponent to be sent in the ideal vision messages.
> Add namespace to id in ideal vision system

- ros2_ws/src/ur_moveit_demo/launch/mtc.launch.py
- ros2_ws/src/ur_moveit_demo/src/mtc.cpp
- ros2_ws/src/ur_moveit_demo/src/vision.cpp
- ros2_ws/src/ur_moveit_demo/src/vision.h
I've modified the MTC code so that the palletization process will start when a robot is detected and not moving. Also, I've added a topic publisher so that the AMR can be notified when the process ends.
> Vision based MTC launch

- Project/Assets/Factory/Objects/WarehouseObjects.prefab
- Project/Levels/DemoLevel1/DemoLevel1.prefab
- ros2_ws/src/blind_path_follower/CMakeLists.txt
- ros2_ws/src/blind_path_follower/launch/blind_path_follower.launch.py
- ros2_ws/src/o3de_fleet_nav/params/humble/nav2_multirobot_params.yaml
- ros2_ws/src/otto_deliberation/include/otto_deliberation/tasks.h
- ros2_ws/src/otto_deliberation/launch/otto_deliberation.launch.py
- ros2_ws/src/otto_deliberation/src/deliberation_otto_node.cpp
- ros2_ws/src/otto_deliberation/src/nav2_action_client.cpp
- ros2_ws/src/otto_deliberation/src/otto_autonomy.cpp
This PR depends on https://github.com/RobotecAI/ROSCon2023Demo/pull/100 and https://github.com/RobotecAI/ROSCon2023Demo/pull/88.
I've integrated the Otto Deliberation with the Lane Service.
This PR consists of some changes:
- Reformated and modified otto_deliberation
- Added statuses for tasks.
- Formated the code.
- Added a launch file (parameters are namespace and assigned_lane)
- Added a launch file for blind path follower (arguments are amr_namespace)
- Modified level to include paths for ur1 and ur2 lanes.
- Fixed broken nav2 parameter files
All paths that include ```approach``` in its name use blind path follower. Others Nav2 navigate through waypoints.
To use this PR launch the Editor with the ros2_ws sourced and launch packages:
- ```ros2 launch o3de_fleet_nav …
```
> Integrate otto deliberation

- Project/Prefabs/OTTO600/OTTO600.prefab
- ros2_ws/src/OTTO600_Description/Urdf/OTTO600.urdf.xacro
> Add missing collider to OTTO600

- Project/Gem/ROSCon2023Demo_files.cmake
- Project/Gem/Source/ROSCon2023DemoModule.cpp
- Project/Gem/Source/Scripting/LifterController.cpp
- Project/Gem/Source/Scripting/LifterController.h
- Project/Prefabs/OTTO600/OTTO600WithPallet.prefab
I've added a component that allows for controlling the otto lifter using ros2 topics.
> Add lifter controller

- Project/Assets/Factory/Objects/PalletStackPayloadFoil1.prefab
- Project/Gem/Source/Scripting/BoxSpawner.cpp
- Project/Gem/Source/Scripting/FoilWrapperController.cpp
- Project/Gem/Source/Scripting/ScriptSpawnLevelComponent.cpp
- Project/Gem/Source/Scripting/ScriptSpawnLevelComponent.h
- Project/Gem/Source/Scripting/ScriptSpawnSytemBus.h
- Project/Levels/TestFoilWrapper/TestFoilWrapper.prefab
Foil wrapper works little more like in real life:
- fixed joint to pallet from boxes, hide visual meshes of original boxes.
- spawn prefab with foil and boxes.
> Changed strategy for wrapper : fixed joint, spawn foil

- Project/Assets/Factory/Objects/PalletStackPayloadFoil1.prefab
- Project/Gem/Source/Scripting/FoilWrapperController.cpp
- Project/Gem/Source/Scripting/FoilWrapperController.h
Include missing changes form #119
> Add hiding boxes during wrapping

- Project/Gem/ROSCon2023Demo_files.cmake
- Project/Gem/Source/HumanNpc/AnimGraphInputProviderComponent.cpp
- Project/Gem/Source/HumanNpc/AnimGraphInputProviderComponent.h
- Project/Gem/Source/HumanNpc/NavigationMeshOrchestratorComponent.cpp
- Project/Gem/Source/HumanNpc/NavigationMeshOrchestratorComponent.h
- Project/Gem/Source/HumanNpc/NpcNavigatorBus.h
- Project/Gem/Source/HumanNpc/NpcNavigatorComponent.cpp
- Project/Gem/Source/HumanNpc/NpcNavigatorComponent.h
- Project/Gem/Source/HumanNpc/WaypointBus.h
- Project/Gem/Source/HumanNpc/WaypointComponent.cpp
- Project/Gem/Source/HumanNpc/WaypointComponent.h
- Project/Gem/Source/HumanNpc/WaypointSelectorComponent.cpp
- Project/Gem/Source/HumanNpc/WaypointSelectorComponent.h
- Project/Gem/Source/ROSCon2023DemoModule.cpp
- Project/Levels/HumanNpcTest/HumanNpcTest.prefab
This pull request:
- extends the current Human Npc with the repeat on traversed toggle
- adds a way to create random waypoint paths with the WaypointSelectorComponent
> Human Npc Improvements

- Project/Gem/Source/Scripting/FoilWrapperController.cpp
- Project/Gem/Source/Scripting/FoilWrapperController.h
- Project/Levels/TestFoilWrapper/TestFoilWrapper.prefab
Due to race conditions foil fixed joints were created to a previous foiled pallet.
> Defuse exploding foil wrapper

- ros2_ws/src/blind_path_follower/src/follow_path.cpp
> Heuristics to improve blind_path_follower

- Project/Gem/Source/Vision/IdealVisionSystem.cpp
- Project/Gem/Source/Vision/IdealVisionSystem.h
> Adjust sensor base to development of o3de-extras

- ros2_ws/src/o3de_fleet_nav/params/humble/nav2_multirobot_params.yaml
I've increased the nav2 speed of robots to 0.7 m/s.
> Increase nav2 speed

- Project/Prefabs/OTTO600/OTTO600WithPallet.prefab
This changes remove not necessary lidar scanners from OTTO600 with pallet.
> Remove not necessary lidar scanners from OTTO600 with pallet.

- Project/Gem/Source/Scripting/FoilWrapperController.cpp
- Project/Levels/TestFoilWrapper/TestFoilWrapper.prefab
> Fixes name collision with payload

- Project/project.json
> Activate and test RGL gem

- Project/Assets/Importer/Otto1500_Otto_1500.material
- Project/Prefabs/OTTO1500_Platform/Otto1500_Platform_A/Otto1500_Platform_A_Otto1500_Platform_A.material
- Project/Prefabs/OTTO600/OTTO600.prefab
- Project/Prefabs/OTTO600/Otto600_Otto600.material
- Project/Prefabs/Otto600-Platform/Otto600Platform_Otto600Platform.material
The materials of Otto 600 were not set correctly. Additionally, applied some tuning of both Ottos' materials.
> Fixed materials of both Ottos

- Project/Levels/DemoLevel1/DemoLevel1.prefab
Main level should include WarehouseObjects_300m2.prefab, not WarehouseObjects.prefab
> Fix for incorect prefab

- Project/Prefabs/OTTO600/OTTO600.prefab
> OTTO600 better lights

- Project/Levels/RobotImportLevel/RobotImportLevel.prefab
Added UR10 robot to RobotImport level. The level was already used in video recording for ROSCon2023.
> update robot import level: add UR10

- Project/autoexec.cfg
- README.md
- ros2_ws/README.md
- ros2_ws/src/roscon2023_demo/config/ROSCon2023Config_4.yaml
- ros2_ws/src/roscon2023_demo/launch/ROSCon2023Demo.launch.py
I've changed the default amount of robots from 8 to 4. I've also reflected in the ros2_ws/readme.md how to change the configuration.
> Change the default amount of robots from 8 to 4

- README.md
I've updated the readme with instructions to use cycloneDDS as the RMW. I've also included setup instructions.
> Update readme to include cyclonedds

- Project/Levels/DemoLevel1/DemoLevel1.prefab
It was different for one spawner
> Fixed spawning rate

- README.md
- ros2_ws/README.md
- ros2_ws/src/ur_palletization/README.md
Typos and formatting were corrected, no changes in the text itself
> update README files

- README.md
- ros2_ws/README.md
- ros2_ws/setup_submodules.bash
- ros2_ws/src/otto_fleet_nav/params/iron/otto1500Params.yaml
- ros2_ws/src/otto_fleet_nav/params/iron/otto600Params.yaml
- ros2_ws/src/ur_palletization/CMakeLists.txt
Should allow building demo for both humble and iron.
- add iron parameters for OTTOs  + fixed palletization cmake,
- add script configuring Universal_Robot_Driver submodule for ros2 humble and iron,
- update documentation.
> Make changes unifying approach for ROS2 humble and iron.

- README.md
There are some variable expansion usages with $ on the wrong side of the curly braces.
> Fix variable expansion in README.md

- ros2_ws/src/blind_path_follower/src/follow_path.cpp
- ros2_ws/src/ur_palletization/src/palletizationNode.cpp
- ros2_ws/src/ur_palletization/src/taskConstructor.cpp
I've cleaned up some warnings form the compilation of the ros2_ws.
> Cleanup workspace warnings

- README.md
* add ros2 navigation stack install guide
* add missing library and tool dependencies
> Add missing dependencies info to README

- Project/Gem/Source/ROSCon2023DemoModule.cpp
This PR fixes line ends in `ROSCon2023DemoModule` file. It solves the issue noticed by @arturkamieniecki in #277
The code was built.
> fix ROSCon2023DemoModule line ends

- Project/Prefabs/Features/HumanNavigation.prefab
- Project/project.json
Updating HumanNavigation prefab to match the new version of the human navigation gem: https://github.com/RobotecAI/o3de-humanworker-gem/pull/8
> Update Human Navigation

- Project/Levels/DemoLevel1/DemoLevel1.prefab
- Project/Levels/DemoLevel2/DemoLevel2.prefab
- Project/Prefabs/Features/HumanNavigation.prefab
- Project/Registry/physxsystemconfiguration.setreg
- Project/Registry/sim_config.setreg
Prevent NPCs from colliding with robots.
Run demo on small scene.
> Prevent NPC collisions, add stable clock and disable mouse capture

- Project/project.json
- README.md
Due to changes in the submodule repo, the code did not build anymore. This was fixed by linking different commit of the submodule by default. Additional fixes and version update were added to the README.
The project was built and run.
> Update UR Driver submodule; Update readme to 2310.3

- Project/Gem/Source/Navigation/LaneComponent.cpp
- Project/Gem/Source/Navigation/LanesServiceComponent.cpp
- Project/Gem/Source/Navigation/SplinePosesPublisher.cpp
- Project/Gem/Source/Scripting/BoxSpawner.cpp
- Project/Gem/Source/Scripting/PayloadDespawnerComponent.cpp
Some components had incorrect serialization. This PR fixes that.
By running the demo for 15 minutes on DemoLevel1.
> Add reference to AZ::Component in serialization
